name: PosePluginReloaded
version: plugin-version
main: ru.armagidon.poseplugin.PosePlugin
api-version: "1.15"
authors: [Armagidon_MC]
description: Give you opportunity to change your pose
softdepend:  [ProtocolLib]
commands:
  posebuilder:
    usage: "/posebuilder [options...]"
  posestop:
    usage: ""